import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Space Travel</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <nav className={styles.navbar}>
        <ul className={styles.navbarList}>
          <li className={styles.navbarListItem}>
            <a href="#about">About</a>
          </li>
          <li className={styles.navbarListItem}>
            <a href="#missions">Program</a>
          </li>
          <li className={styles.navbarListItem}>
            <a href="#ourTeam">Our Team</a>
          </li>
        </ul>
        <ConnectButton />
      </nav>

      <main className={styles.main}>
      <div className={styles.hero}>
        <h1>INFINITY VENTURES</h1>
        <p>"Exploring infinite possibilities, creating valuable ventures."</p>
      </div>
      <div className={styles.aboutSection} id="about">
        <h2>About SpaceX</h2>
        <p>
        We are a space travel agency dedicated to providing a unique and unforgettable travel experience. We work in collaboration with SpaceX to offer our customers the opportunity to travel to space and experience the thrill of exploring the universe.

        At Infinity Ventures, we are passionate about technology and innovation, and we believe that space is the next natural step in our exploration as a species. That's why we strive to provide a safe and exciting space travel experience for our customers.

        Our travel packages are designed to offer a personalized and unique experience for each customer. From space accommodations to exciting zero-gravity activities, we make sure our customers enjoy every moment of their space travel.

        At Infinity Ventures, we are committed to providing exceptional service and an unforgettable travel experience. We look forward to taking our customers on a unique and exciting adventure towards the stars.
        </p>
      </div>
      <div className={styles.missionsSection} id="missions">
        <h2>Our trips</h2>
        <p>
        SpaceX is a leading space technology company dedicated to taking space exploration to new heights. Since its founding in 2002, SpaceX has achieved numerous industry milestones, including launching the first reusable rocket and sending the first commercial crewed mission to the International Space Station. With a focus on technology and innovation, SpaceX is working to make space travel more accessible and affordable for everyone.

        If you're interested in booking your own space journey with SpaceX, you can do so through our dApp. With the dApp, you'll be able to explore the different mission options available, select your desired date and destination, and make your reservation online. You'll also have access to important information about pre-flight requirements and the safety measures taken to ensure a safe and thrilling travel experience. Don't wait any longer to reserve your spot on the next SpaceX mission!
        </p>
      </div>
      <div className={styles.newsSection} id="ourTeam">
      <h2>Meet Our Team</h2>
      <p>At SpaceX, we have a diverse and talented team of individuals who work tirelessly to push the boundaries of space exploration and technology. Led by our CEO and Chief Engineer, Elon Musk, our team includes experts in rocket propulsion, mission management, crew operations, build and flight reliability, and much more.

      Gwynne Shotwell, our President and COO, is responsible for overseeing day-to-day operations and ensuring our goals are met efficiently and effectively. Tom Mueller, our Propulsion Chief Technology Officer, leads the development of our powerful rocket engines, while Hans Koenigsmann, our Vice President of Build and Flight Reliability, ensures that our rockets are built and launched safely and reliably.

      Garrett Reisman, our Director of Crew Operations, oversees the training and management of our astronaut crews, and Jessica Jensen, our Director of Dragon Mission Management, leads the planning and execution of our Dragon spacecraft missions.

      Overall, our team is driven by a shared passion for space exploration and a commitment to pushing the limits of what's possible. We're proud to be at the forefront of this exciting industry and can't wait to see what the future holds.
      </p>
      </div>
     
      </main>

      <footer className={styles.footer}>
        <ul>
          <li><a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
            Made with ❤️ by your frens at 🌈
          </a></li>
        <li className={styles.navbarListItem}>
            <a href="https://www.instagram.com/spacex/" target="_blank">Instagram</a>
          </li>
          <li className={styles.navbarListItem}>
            <a href="https://twitter.com/SpaceX" target="_blank">Twitter</a>
          </li>
        </ul>
      </footer>
    </div>

  );
};

export default Home;
