import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useMediaQuery } from 'react-responsive';
import 'bootstrap/dist/css/bootstrap.min.css';
import { Navbar, Nav, NavDropdown } from 'react-bootstrap';
import { useRouter } from "next/router";
import { useAccount } from "wagmi";
import App from '../src/App';

const Home: NextPage = () => {
  const { isConnected } = useAccount();
  const router = useRouter();

  

  const isSmallScreen = useMediaQuery({ query: '(max-width: 600px)' });
  return (
    <><div className={styles.container}>
      {isSmallScreen ? (
            <>
            <Head>
              <title>Space Travel</title>
              <meta
                content="Generated by @rainbow-me/create-rainbowkit"
                name="description" />
              <link href="/favicon.ico" rel="icon" />
            </Head>
              <Nav className={styles.navbar}>
              <NavDropdown title="Menu" id="basic-nav-dropdown">
              <NavDropdown.Item href="#about">About</NavDropdown.Item>
              <NavDropdown.Item href="#missions">Our Trips</NavDropdown.Item>
              <NavDropdown.Item href="#ourTeam">Our Team</NavDropdown.Item>
            </NavDropdown>
                <ConnectButton />
                {isConnected ? <App/> : null } 
              </Nav>
              <main className={styles.main}>

                <div className={styles.hero}>
                  <h1>INFINITY VENTURES</h1>
                  <p>"Exploring infinite possibilities, creating valuable ventures."</p>
                </div>
                <div className={styles.aboutSection} id="about">
                  <h2>About SpaceX</h2>
                  <p>
                    We are a space travel agency dedicated to providing a unique and unforgettable travel experience. We work in collaboration with SpaceX to offer our customers the opportunity to travel to space and experience the thrill of exploring the universe.
                  </p>
                </div>
                <div className={styles.missionsSection} id="missions">
                  <h2>Our trips</h2>
                  <p>
                    SpaceX is a leading space technology company dedicated to taking space exploration to new heights. Since its founding in 2002, SpaceX has achieved numerous industry milestone.

                  </p>
                </div>
                <div className={styles.newsSection} id="ourTeam">
                  <h2>Meet Our Team</h2>
                  <p>At SpaceX, we have a diverse and talented team of individuals who work tirelessly to push the boundaries of space exploration and technology. Led by our CEO and Chief Engineer, Elon Musk, our team includes experts in rocket propulsion, mission management, crew operations, build and flight reliability, and much more.
                  </p>
                </div>

              </main>
              <footer className={styles.footer}>
                <ul>

                  <li className={styles.navbarListItem}>
                    <a href="https://www.instagram.com/spacex/" target="_blank">Instagram</a>
                  </li>
                  <li className={styles.navbarListItem}>
                    <a href="https://twitter.com/SpaceX" target="_blank">Twitter</a>
                  </li>
                </ul>
              </footer></>
          ) : (
            <>
            <nav className={styles.navbar}>
                <ul className={styles.navbarList}>
                  <li className={styles.navbarListItem}>
                    <a href="#about">About</a>
                  </li>
                  <li className={styles.navbarListItem}>
                    <a href="#missions">Program</a>
                  </li>
                  <li className={styles.navbarListItem}>
                    <a href="#ourTeam">Our Team</a>
                  </li>
                </ul>
                <ConnectButton />
              </nav>
            <main className={styles.main}>

                <div className={styles.hero}>
                  <h1>INFINITY VENTURES</h1>
                  <p>"Exploring infinite possibilities, creating valuable ventures."</p>
                </div>
                <div className={styles.aboutSection} id="about">
                  <h2>About SpaceX</h2>
                  <p>
                   We are a space travel agency dedicated to providing a unique and unforgettable travel experience. We work in collaboration with SpaceX to offer our customers the opportunity to travel to space and experience the thrill of exploring the universe.

                  </p>
                </div>
                <div className={styles.missionsSection} id="missions">
                  <h2>Our trips</h2>
                  <p>
                    SpaceX is a leading space technology company dedicated to taking space exploration to new heights. Since its founding in 2002, SpaceX has achieved numerous industry milestones, including launching the first reusable rocket and sending the first commercial crewed mission to the International Space Station. With a focus on technology and innovation, SpaceX is working to make space travel more accessible and affordable for everyone.

                  </p>
                </div>
                <div className={styles.newsSection} id="ourTeam">
                  <h2>Meet Our Team</h2>
                  <p>At SpaceX, we have a diverse and talented team of individuals who work tirelessly to push the boundaries of space exploration and technology. Led by our CEO and Chief Engineer, Elon Musk, our team includes experts in rocket propulsion, mission management, crew operations, build and flight reliability, and much more.
                  </p>
                </div>

              </main>
            <footer className={styles.footer}>
              <ul>

                <li className={styles.navbarListItem}>
                  <a href="https://www.instagram.com/spacex/" target="_blank">Instagram</a>
                </li>
                <li className={styles.navbarListItem}>
                  <a href="https://twitter.com/SpaceX" target="_blank">Twitter</a>
                </li>
              </ul>
            </footer>
            </>
          )}
  
    </div></>

  )};

export default Home;
